//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OM.Notifications.Facade.WsNotificationsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageVariable", Namespace="http://schemas.datacontract.org/2004/07/OM.Notifications.Entities")]
    [System.SerializableAttribute()]
    public partial class MessageVariable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageAttachment", Namespace="http://schemas.datacontract.org/2004/07/OM.Notifications.Entities")]
    [System.SerializableAttribute()]
    public partial class MessageAttachment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EncryptionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MediaTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EncryptionKey {
            get {
                return this.EncryptionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptionKeyField, value) != true)) {
                    this.EncryptionKeyField = value;
                    this.RaisePropertyChanged("EncryptionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MediaType {
            get {
                return this.MediaTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.MediaTypeField, value) != true)) {
                    this.MediaTypeField = value;
                    this.RaisePropertyChanged("MediaType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageContact", Namespace="http://schemas.datacontract.org/2004/07/OM.Notifications.Entities")]
    [System.SerializableAttribute()]
    public partial class MessageContact : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnlineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageBodyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OM.Notifications.Facade.WsNotificationsService.ContactRecipient RecipientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private OM.Notifications.Facade.WsNotificationsService.MessageType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnifiedReferenceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnline {
            get {
                return this.IsOnlineField;
            }
            set {
                if ((this.IsOnlineField.Equals(value) != true)) {
                    this.IsOnlineField = value;
                    this.RaisePropertyChanged("IsOnline");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageBody {
            get {
                return this.MessageBodyField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageBodyField, value) != true)) {
                    this.MessageBodyField = value;
                    this.RaisePropertyChanged("MessageBody");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OM.Notifications.Facade.WsNotificationsService.ContactRecipient Recipient {
            get {
                return this.RecipientField;
            }
            set {
                if ((this.RecipientField.Equals(value) != true)) {
                    this.RecipientField = value;
                    this.RaisePropertyChanged("Recipient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OM.Notifications.Facade.WsNotificationsService.MessageType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnifiedReference {
            get {
                return this.UnifiedReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.UnifiedReferenceField, value) != true)) {
                    this.UnifiedReferenceField = value;
                    this.RaisePropertyChanged("UnifiedReference");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactRecipient", Namespace="http://schemas.datacontract.org/2004/07/OM.Notifications.Entities")]
    public enum ContactRecipient : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Customer = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Agent = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageType", Namespace="http://schemas.datacontract.org/2004/07/OM.Notifications.Entities")]
    public enum MessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsNotificationsService.INotificationsService")]
    public interface INotificationsService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationsService/SendMessage", ReplyAction="http://tempuri.org/INotificationsService/SendMessageResponse")]
        void SendMessage(int operationId, string docNumber, string docType, int contractNumber, string productCode, decimal amount, OM.Notifications.Facade.WsNotificationsService.MessageVariable[] variables, System.Nullable<bool> sendToFpOnly);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationsService/SendMessageWithAttachments", ReplyAction="http://tempuri.org/INotificationsService/SendMessageWithAttachmentsResponse")]
        void SendMessageWithAttachments(int operationId, string from, string to, string subject, OM.Notifications.Facade.WsNotificationsService.MessageVariable[] variables, OM.Notifications.Facade.WsNotificationsService.MessageAttachment[] attachments, OM.Notifications.Facade.WsNotificationsService.MessageContact[] contactsBcc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationsService/SendMessageWithContacts", ReplyAction="http://tempuri.org/INotificationsService/SendMessageWithContactsResponse")]
        void SendMessageWithContacts(int operationId, string docNumber, string docType, int contractNumber, decimal amount, OM.Notifications.Facade.WsNotificationsService.MessageVariable[] variables, OM.Notifications.Facade.WsNotificationsService.MessageContact[] contacts);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationsService/GetMessageTemplate", ReplyAction="http://tempuri.org/INotificationsService/GetMessageTemplateResponse")]
        string GetMessageTemplate(int operationId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationsServiceChannel : OM.Notifications.Facade.WsNotificationsService.INotificationsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationsServiceClient : System.ServiceModel.ClientBase<OM.Notifications.Facade.WsNotificationsService.INotificationsService>, OM.Notifications.Facade.WsNotificationsService.INotificationsService {
        
        public NotificationsServiceClient() {
        }
        
        public NotificationsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificationsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SendMessage(int operationId, string docNumber, string docType, int contractNumber, string productCode, decimal amount, OM.Notifications.Facade.WsNotificationsService.MessageVariable[] variables, System.Nullable<bool> sendToFpOnly) {
            base.Channel.SendMessage(operationId, docNumber, docType, contractNumber, productCode, amount, variables, sendToFpOnly);
        }
        
        public void SendMessageWithAttachments(int operationId, string from, string to, string subject, OM.Notifications.Facade.WsNotificationsService.MessageVariable[] variables, OM.Notifications.Facade.WsNotificationsService.MessageAttachment[] attachments, OM.Notifications.Facade.WsNotificationsService.MessageContact[] contactsBcc) {
            base.Channel.SendMessageWithAttachments(operationId, from, to, subject, variables, attachments, contactsBcc);
        }
        
        public void SendMessageWithContacts(int operationId, string docNumber, string docType, int contractNumber, decimal amount, OM.Notifications.Facade.WsNotificationsService.MessageVariable[] variables, OM.Notifications.Facade.WsNotificationsService.MessageContact[] contacts) {
            base.Channel.SendMessageWithContacts(operationId, docNumber, docType, contractNumber, amount, variables, contacts);
        }
        
        public string GetMessageTemplate(int operationId) {
            return base.Channel.GetMessageTemplate(operationId);
        }
    }
}
